#!/usr/bin/env node
/**
 * Textdraw Editor smoke test / demo generator.
 *
 * Runs the TextdrawManager against a throwaway SA-MP server root (written to
 * .freebuff/textdraw-demo, which is git-ignored):
 *
 *  1. synthesizes a real .txd dictionary (one uncompressed 8888 texture and one
 *     DXT1 texture) so the TXD parser, the DXT decoder and the PNG encoder are
 *     exercised end to end,
 *  2. imports TextDrawCreate code from a fake gamemode,
 *  3. creates sprite / model-preview / boxed textdraws,
 *  4. scans the dictionaries and renders the preview page (assets inlined).
 *
 * Run: node scripts/textdraw-demo.mjs   (after `npm run build`)
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { TextdrawManager } from '../dist/textdraw.js';
import { parseTxd, decodeTxdTexture } from '../dist/txd.js';

const root = path.join(import.meta.dirname, '..', '.freebuff', 'textdraw-demo');

function chunk(type, payload) {
    const header = Buffer.alloc(12);
    header.writeUInt32LE(type, 0);
    header.writeUInt32LE(payload.length, 4);
    header.writeUInt32LE(0x1803ffff, 8);
    return Buffer.concat([header, payload]);
}

/** A 64x64 8888 (BGRA) texture: colour gradient with an alpha corner. */
function gradientTexture() {
    const size = 64;
    const pixels = Buffer.alloc(size * size * 4);
    for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
            const o = (y * size + x) * 4;
            pixels[o] = Math.round((x / (size - 1)) * 255); // B
            pixels[o + 1] = Math.round((y / (size - 1)) * 255); // G
            pixels[o + 2] = 40; // R
            pixels[o + 3] = x < 8 && y < 8 ? 0 : 255; // A
        }
    }
    return pixels;
}

/** A 16x16 DXT1 texture: solid red blocks so the decoder output is predictable. */
function dxt1Texture() {
    const block = Buffer.alloc(8);
    block.writeUInt16LE(0xf800, 0); // c0 = red
    block.writeUInt16LE(0x001f, 1 + 1); // c1 = blue (c0 > c1 → 4-colour mode)
    block.writeUInt32LE(0x00000000, 4); // all pixels use c0
    return Buffer.concat(new Array(16).fill(block));
}

/**
 * One texture-native section with the real SA header layout (92 bytes, pixels
 * follow immediately) — see src/txd.ts for the field-by-field notes.
 */
function textureNative({ name, width, height, rasterFormat, d3dFormat, flags, data }) {
    const header = Buffer.alloc(92);
    header.writeUInt32LE(9, 0); // platform: Direct3D 9 (GTA SA)
    header.writeUInt32LE(0x1102, 4); // filter mode / addressing
    header.write(name, 8, 32, 'latin1');
    header.writeUInt32LE(rasterFormat, 72);
    header.writeUInt32LE(d3dFormat, 76);
    header.writeUInt16LE(width, 80);
    header.writeUInt16LE(height, 82);
    header.writeUInt8(32, 84); // depth
    header.writeUInt8(1, 85); // one mip level
    header.writeUInt8(4, 86); // raster type
    header.writeUInt8(flags, 87);
    header.writeUInt32LE(data.length, 88);

    return chunk(0x15, Buffer.concat([
        chunk(0x01, Buffer.concat([header, data])),
    ]));
}

function buildDictionary() {
    const dictionaryStruct = Buffer.alloc(4);
    dictionaryStruct.writeUInt16LE(2, 0); // two textures
    dictionaryStruct.writeUInt16LE(9, 2);
    const uncompressed = gradientTexture();
    const compressed = dxt1Texture();
    return chunk(0x16, Buffer.concat([
        chunk(0x01, dictionaryStruct),
        textureNative({
            name: 'demo_logo',
            width: 64,
            height: 64,
            rasterFormat: 0x0500, // FORMAT_8888
            d3dFormat: 21, // D3DFMT_A8R8G8B8
            flags: 0x01, // has alpha
            data: uncompressed,
        }),
        textureNative({
            name: 'demo_icon',
            width: 16,
            height: 16,
            rasterFormat: 0x0200, // FORMAT_565 (DXT1 without alpha)
            d3dFormat: 0x31545844, // 'DXT1'
            flags: 0x08, // compressed
            data: compressed,
        }),
    ]));
}

const pawnSource = `// demo gamemode (generated by scripts/textdraw-demo.mjs)
#include <a_samp>

new Text:gServerName;
new Text:gMoneyBox;
new PlayerText:pHungerBar[MAX_PLAYERS];

public OnGameModeInit()
{
    gServerName = TextDrawCreate(320.0, 20.0, "DEMO ROLEPLAY");
    TextDrawLetterSize(gServerName, 0.4, 1.8);
    TextDrawAlignment(gServerName, 2);
    TextDrawColor(gServerName, 0xFFCC00FF);
    TextDrawSetOutline(gServerName, 1);
    TextDrawSetShadow(gServerName, 0);
    TextDrawSetProportional(gServerName, 1);
    TextDrawFont(gServerName, 1);

    gMoneyBox = TextDrawCreate(20.0, 400.0, "Money: $1,250");
    TextDrawUseBox(gMoneyBox, 1);
    TextDrawBoxColor(gMoneyBox, 0x000000AA);
    TextDrawTextSize(gMoneyBox, 150.0, 430.0);
    TextDrawLetterSize(gMoneyBox, 0.25, 1.0);
    TextDrawColor(gMoneyBox, 0x39FF88FF);
    TextDrawFont(gMoneyBox, 2);
    return 1;
}

public OnPlayerConnect(playerid)
{
    pHungerBar[playerid] = CreatePlayerTextDraw(playerid, 560.0, 340.0, "Hunger");
    PlayerTextDrawLetterSize(playerid, pHungerBar[playerid], 0.2, 0.9);
    PlayerTextDrawColor(playerid, pHungerBar[playerid], 0xFFFFFFFF);
    PlayerTextDrawUseBox(playerid, pHungerBar[playerid], 1);
    PlayerTextDrawBoxColor(playerid, pHungerBar[playerid], 0x00000099);
    PlayerTextDrawTextSize(playerid, pHungerBar[playerid], 90.0, 10.0);
    PlayerTextDrawFont(playerid, pHungerBar[playerid], 0);
    return 1;
}
`;

async function main() {
    await rm(root, { recursive: true, force: true });
    await mkdir(path.join(root, 'models', 'txd'), { recursive: true });
    await mkdir(path.join(root, 'gamemodes'), { recursive: true });

    // 1. synthetic dictionary + a fake gamemode to import from
    const txd = buildDictionary();
    await writeFile(path.join(root, 'models', 'txd', 'demo.txd'), txd);
    await writeFile(path.join(root, 'gamemodes', 'main.pwn'), pawnSource, 'utf8');

    const parsed = parseTxd(txd, 'demo.txd');
    const icon = decodeTxdTexture(txd, 'demo_icon');
    console.log('TXD parse:', parsed.name, parsed.version, parsed.textures.map((t) => `${t.name} ${t.width}x${t.height} ${t.format}`).join(', '));
    console.log('DXT1 decode:', icon ? `${icon.width}x${icon.height} first pixel rgba=${[...icon.rgba.subarray(0, 4)].join(',')}` : 'FAILED');

    const manager = new TextdrawManager();
    manager.setRoot(root);

    // 2. import the legacy textdraws
    const imported = await manager.importFromScript('demo', 'gamemodes/main.pwn', 'merge');
    console.log('Import:', `${imported.imported} textdraws (${imported.created.join(', ')}) from ${imported.files.join(', ')}`);

    // 3. a sprite logo (font 4) + a model preview (font 5) + a Thai boxed panel
    await manager.createTextdraw('demo', {
        name: 'gLogo',
        text: 'demo:demo_logo',
        font: 4,
        x: 40,
        y: 40,
        textSizeX: 64,
        textSizeY: 64,
        box: true,
        boxColor: '0x101820CC',
        group: 'branding',
    });
    await manager.createTextdraw('demo', {
        name: 'gIconBadge',
        text: 'demo:demo_icon',
        font: 4,
        x: 120,
        y: 44,
        textSizeX: 32,
        textSizeY: 32,
        group: 'branding',
    });
    await manager.createTextdraw('demo', {
        name: 'gWeaponPreview',
        text: '',
        font: 5,
        x: 250,
        y: 70,
        textSizeX: 60,
        textSizeY: 60,
        previewModel: 355,
        previewRot: [0, 0, 0],
        previewZoom: 1.2,
        group: 'hud',
    });
    await manager.createTextdraw('demo', {
        name: 'gPanel',
        text: 'ยินดีต้อนรับ\nWelcome to the server',
        font: 1,
        x: 320,
        y: 150,
        alignment: 2,
        letterWidth: 0.3,
        letterHeight: 1.2,
        textSizeX: 220,
        textSizeY: 90,
        box: true,
        boxColor: '0x1E2A38E6',
        color: '0xFFFFFFFF',
        outline: 1,
        group: 'hud',
    });

    // 4. dictionaries + preview page
    const scan = await manager.scanTxds({ depth: 3, exportPng: true, maxTextureSize: 256, limit: 32 });
    console.log('TXD scan:', `${scan.scannedFiles} file(s)`, scan.textures.map((t) => `${t.key} (${t.format}, decodable=${t.decodable})`).join(', '));

    const preview = await manager.buildPreview('demo', { exportPng: true, inlineAssets: true, maxTextureSize: 256 });
    console.log('Preview:', preview.htmlPath);
    console.log('Textdraws rendered:', preview.textdraws, '· sprites resolved:', preview.assets);
    console.log('Unresolved sprites:', preview.missingTextures.length ? preview.missingTextures.join(', ') : 'none');
    console.log('Warnings:', preview.warnings.length ? '\n  ' + preview.warnings.join('\n  ') : 'none');

    const exported = await manager.exportTextdraws('demo', { mode: 'statements', target: 'all' });
    console.log('\n--- Pawn export (first 12 lines) ---');
    console.log(exported.content.split('\n').slice(0, 12).join('\n'));

    // 5. round trip: import -> export -> import must not change any property
    const BS = String.fromCharCode(92);
    const newline = String.fromCharCode(10);
    await writeFile(path.join(root, 'gamemodes', 'roundtrip.pwn'), [
        'new Text:gRoundTrip;',
        'public OnGameModeInit()',
        '{',
        `    gRoundTrip = TextDrawCreate(320.0, 100.5, "Line1${BS}nLine2 _ tail");`,
        '    TextDrawLetterSize(gRoundTrip, 0.3125, 1.44);',
        '    TextDrawTextSize(gRoundTrip, 100.0, 250.0);',
        '    TextDrawAlignment(gRoundTrip, 2);',
        '    TextDrawColor(gRoundTrip, 0xE1E1E1FF);',
        '    TextDrawFont(gRoundTrip, 2);',
        '    return 1;',
        '}',
        '',
    ].join(newline), 'utf8');
    await manager.importFromScript('rt', 'gamemodes/roundtrip.pwn', 'replace');
    const rtBefore = (await manager.listTextdraws('rt', {})).textdraws[0];
    const rtExport = await manager.exportTextdraws('rt', { mode: 'statements' });
    await writeFile(path.join(root, 'gamemodes', 'roundtrip-exported.pwn'), rtExport.content, 'utf8');
    await manager.importFromScript('rt2', 'gamemodes/roundtrip-exported.pwn', 'replace');
    const rtAfter = (await manager.listTextdraws('rt2', {})).textdraws[0];
    const diffs = Object.keys(rtBefore).filter((key) => JSON.stringify(rtBefore[key]) !== JSON.stringify(rtAfter[key]));
    const createLine = rtExport.content.split(newline).find((line) => line.includes('TextDrawCreate'));
    console.log('\n--- Round trip (Pawn -> project -> Pawn -> project) ---');
    console.log('re-exported create:', createLine);
    if (diffs.length) {
        console.error('ROUND TRIP FAILED, differing properties: ' + diffs.join(', '));
        process.exit(1);
    }
    console.log(`ROUND TRIP OK: ${Object.keys(rtBefore).length} properties identical (newlines escaped as ${BS}n, "_" kept for the client)`);
}

main().catch((error) => {
    console.error('demo failed:', error);
    process.exit(1);
});
